app/django/_pdf/urls.py
from django.urls import path
from .views import *

app_name = 'pdf'

urlpatterns = [
    # pdf url
    path('bill/', PdfExportBill.as_view(), name='bill'),
    path('payments/', PdfExportPayments.as_view(), name='payments'),
]

app/django/api/urls.py
from django.urls import path

from rest_framework.response import Response
from rest_framework.reverse import reverse

from .views.accounts import *
from .views.company import *
from .views.rebs import *
from .views.project import *
from .views.cash import *
from .views.contract import *
from .views.notice import *
from .views.document import *


class ApiIndex(generics.GenericAPIView):
    name = 'api-index'
    permission_classes = (permissions.AllowAny,)

    def get(self, request, *args, **kwargs):
        api = 'api:'
        return Response({
            # accounts
            'user': reverse(api + 'user-list', request=request),
            'profile': reverse(api + 'profile-list', request=request),
            'todo': reverse(api + 'todo-list', request=request),
            # company
            'company': reverse(api + 'company-list', request=request),
            'logo': reverse(api + 'logo-list', request=request),
            'department': reverse(api + 'depart-list', request=request),
            'position': reverse(api + 'position-list', request=request),
            'staff': reverse(api + 'staff-list', request=request),
            # rebs
            'schedule': reverse(api + 'schedule-list', request=request),
            'account-sort': reverse(api + AccountSortList.name, request=request),
            'account-depth1': reverse(api + AccountSubD1List.name, request=request),
            'account-depth2': reverse(api + AccountSubD2List.name, request=request),
            'account-depth3': reverse(api + AccountSubD3List.name, request=request),
            'project-acc-sort': reverse(api + ProjectAccountSortList.name, request=request),
            'project-acc-d1': reverse(api + ProjectAccountD1List.name, request=request),
            'project-acc-d2': reverse(api + ProjectAccountD2List.name, request=request),
            'wise-say': reverse(api + WiseSayList.name, request=request),
            # project
            'project': reverse(api + 'project-list', request=request),
            'type': reverse(api + 'unittype-list', request=request),
            'floor': reverse(api + 'floortype-list', request=request),
            'key-unit': reverse(api + 'key_unit-list', request=request),
            'bldg-unit': reverse(api + 'bldg-list', request=request),
            'house-unit': reverse(api + HouseUnitList.name, request=request),
            'available-house-unit': reverse(api + AvailableHouseUnitList.name, request=request),
            'all-house-unit': reverse(api + AllHouseUnitList.name, request=request),
            'budget': reverse(api + ProjectBudgetList.name, request=request),
            'exec-amount-budget': reverse(api + ExecAmountToBudgetList.name, request=request),
            'all-site': reverse(api + AllSiteList.name, request=request),
            'sites-total': reverse(api + TotalSiteArea.name, request=request),
            'site': reverse(api + 'site-list', request=request),
            'all-owner': reverse(api + AllOwnerList.name, request=request),
            'owners-total': reverse(api + TotalOwnerArea.name, request=request),
            'site-owner': reverse(api + 'siteowner-list', request=request),
            'site-relation': reverse(api + 'relation-list', request=request),
            'conts-total': reverse(api + TotalContractedArea.name, request=request),
            'site-contract': reverse(api + 'sitecontract-list', request=request),
            # cash
            'bank-code': reverse(api + BankCodeList.name, request=request),
            'com-bank': reverse(api + 'com_bank-list', request=request),
            'balance-by-acc': reverse(api + BalanceByAccountList.name, request=request),
            'cashbook': reverse(api + CashBookList.name, request=request),
            'date-cashbook': reverse(api + DateCashBookList.name, request=request),
            'project-bank': reverse(api + ProjectBankAccountList.name, request=request),
            'pr-balance-by-acc': reverse(api + PrBalanceByAccountList.name, request=request),
            'pr-date-cashbook': reverse(api + ProjectDateCashBookList.name, request=request),
            'project-cashbook': reverse(api + ProjectCashBookList.name, request=request),
            'project-imprest': reverse(api + ProjectImprestList.name, request=request),
            'payment-list': reverse(api + PaymentList.name, request=request),
            'all-payment-list': reverse(api + AllPaymentList.name, request=request),
            'payment-sum': reverse(api + PaymentSummary.name, request=request),
            'cont-count': reverse(api + NumContractByType.name, request=request),
            'price': reverse(api + SalesPriceList.name, request=request),
            'pay-order': reverse(api + InstallmentOrderList.name, request=request),
            'down-payment': reverse(api + DownPaymentList.name, request=request),
            # 'over-due-rule': reverse(api + OverDueRuleList.name, request=request),
            # contract
            'order-group': reverse(api + 'order_group-list', request=request),
            'contract': reverse(api + 'contract-list', request=request),
            'contract-custom-list': reverse(api + 'contract-cumstom-list', request=request),
            'subs-sum': reverse(api + SubsSummaryList.name, request=request),
            'cont-sum': reverse(api + ContSummaryList.name, request=request),
            'contractor': reverse(api + 'contractor-list', request=request),
            'contractor-address': reverse(api + 'cont_address-list', request=request),
            'contractor-contact': reverse(api + 'contact-list', request=request),
            'contractor-release': reverse(api + 'release-list', request=request),
            # notice
            'sales-bill-issue': reverse(api + BillIssueList.name, request=request),
            # document
            'group': reverse(api + GroupList.name, request=request),
            'board': reverse(api + BoardList.name, request=request),
            'category': reverse(api + CategoryList.name, request=request),
            'suitcase': reverse(api + LawSuitCaseList.name, request=request),
            'post': reverse(api + PostList.name, request=request),
            'image': reverse(api + ImageList.name, request=request),
            'link': reverse(api + LinkList.name, request=request),
            'file': reverse(api + FileList.name, request=request),
            'comment': reverse(api + CommentList.name, request=request),
            'tag': reverse(api + TagList.name, request=request),
        })


app_name = 'api'

list_view = {'get': 'list', 'post': 'create'}
detail_view = {
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
}

urlpatterns = [
    # accounts
    path('', ApiIndex.as_view(), name=ApiIndex.name),
    path('user/', UserViewSets.as_view(list_view), name='user-list'),
    path('user/<int:pk>/', UserViewSets.as_view(detail_view), name='user-detail'),
    path('profile/', ProfileViewSets.as_view(list_view), name='profile-list'),
    path('profile/<int:pk>/', ProfileViewSets.as_view(detail_view), name='profile-detail'),
    path('todo/', TodoViewSets.as_view(list_view), name='todo-list'),
    path('todo/<int:pk>/', TodoViewSets.as_view(detail_view), name='todo-detail'),
    # company
    path('company/', CompanyViewSets.as_view(list_view), name='company-list'),
    path('company/<int:pk>/', CompanyViewSets.as_view(detail_view), name='company-detail'),
    path('logo/', LogoViewSets.as_view(list_view), name='logo-list'),
    path('logo/<int:pk>/', LogoViewSets.as_view(detail_view), name='logo-detail'),
    path('department/', DepartmentViewSets.as_view(list_view), name='depart-list'),
    path('department/<int:pk>/', DepartmentViewSets.as_view(detail_view), name='depart-detail'),
    path('position/', PositionViewSets.as_view(list_view), name='position-list'),
    path('position/<int:pk>/', PositionViewSets.as_view(detail_view), name='position-detail'),
    path('staff/', StaffViewSets.as_view(list_view), name='staff-list'),
    path('staff/<int:pk>/', StaffViewSets.as_view(detail_view), name='staff-detail'),
    # rebs
    path('schedule/', CalendarScheduleViewSet.as_view(list_view), name='schedule-list'),
    path('schedule/<int:pk>/', CalendarScheduleViewSet.as_view(detail_view), name='schedule-detail'),
    path('account-sort/', AccountSortList.as_view(), name=AccountSortList.name),
    path('account-depth1/', AccountSubD1List.as_view(), name=AccountSubD1List.name),
    path('account-depth2/', AccountSubD2List.as_view(), name=AccountSubD2List.name),
    path('account-depth3/', AccountSubD3List.as_view(), name=AccountSubD3List.name),
    path('project-acc-sort/', ProjectAccountSortList.as_view(), name=ProjectAccountSortList.name),
    path('project-account-depth1/', ProjectAccountD1List.as_view(), name=ProjectAccountD1List.name),
    path('project-account-depth2/', ProjectAccountD2List.as_view(), name=ProjectAccountD2List.name),
    path('wise-say/', WiseSayList.as_view(), name=WiseSayList.name),
    path('wise-say/<int:pk>/', WiseSayDetail.as_view(), name=WiseSayDetail.name),
    # project
    path('project/', ProjectViewSets.as_view(list_view), name='project-list'),
    path('project/<int:pk>/', ProjectViewSets.as_view(detail_view), name='project-detail'),
    path('type/', UnitTypeViewSets.as_view(list_view), name='unittype-list'),
    path('type/<int:pk>/', UnitTypeViewSets.as_view(detail_view), name='unittype-detail'),
    path('floor/', UnitFloorTypeViewSets.as_view(list_view), name='floortype-list'),
    path('floor/<int:pk>/', UnitFloorTypeViewSets.as_view(detail_view), name='floortype-detail'),
    path('key-unit/', KeyUnitViewSets.as_view(list_view), name='key_unit-list'),

app/django/notice/urls.py
from django.urls import path
from .views import *

app_name = 'notice'

urlpatterns = [
    path('bill/', BillManageView.as_view(), name='bill'),
]

app/django/notice/models.py
from django.db import models
from django.conf import settings
from import_export.admin import ImportExportMixin


class SalesBillIssue(ImportExportMixin, models.Model):
    project = models.OneToOneField('project.Project', on_delete=models.CASCADE, verbose_name='프로젝트')
    now_payment_order = models.ForeignKey('payment.InstallmentPaymentOrder', on_delete=models.CASCADE,
                                          verbose_name='현재 발행회차')
    host_name = models.CharField('시행자명', max_length=20)
    host_tel = models.CharField('시행사 전화', max_length=13)
    agency = models.CharField('대행사명', max_length=20, blank=True)
    agency_tel = models.CharField('대행사 전화', max_length=13, blank=True)
    bank_account1 = models.CharField('수납은행[1]', max_length=20)
    bank_number1 = models.CharField('계좌번호[1]', max_length=25)
    bank_host1 = models.CharField('예금주[1]', max_length=20)
    bank_account2 = models.CharField('수납은행[2]', max_length=20, blank=True)
    bank_number2 = models.CharField('계좌번호[2]', max_length=25, blank=True)
    bank_host2 = models.CharField('예금주[2]', max_length=20, blank=True)
    zipcode = models.CharField('우편번호', max_length=5)
    address1 = models.CharField('주소', max_length=35)
    address2 = models.CharField('상세주소', max_length=20, blank=True)
    address3 = models.CharField('참고항목', max_length=20, blank=True)
    title = models.CharField('고지서 제목', max_length=80)
    content = models.TextField('고지서 내용')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='등록자')
    updated_at = models.DateTimeField('최종 변경일', auto_now=True)

    class Meta:
        ordering = ['id']
        verbose_name = "01. 프로젝트 고지서 정보"
        verbose_name_plural = "01. 프로젝트 고지서 정보"

    def __str__(self):
        return f'{self.project}-고지서 정보'

app/django/notice/forms.py
from django import forms
from payment.models import InstallmentPaymentOrder


class SalesBillIssueForm(forms.Form):
    # project = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'project'}))
    published_date = forms.DateField(label='발행일자')
    now_payment_order = forms.ModelChoiceField(queryset=InstallmentPaymentOrder.objects.all(), label='발행회차')
    now_due_date = forms.DateField(label='당회 납부기한', required=False)
    host_name = forms.CharField(max_length=20, label='시행자명')
    host_tel = forms.CharField(max_length=13, label='시행자 전화')
    agency = forms.CharField(max_length=20, label='대행사명', required=False)
    agency_tel = forms.CharField(max_length=13, label='대행사 전화', required=False)
    bank_account1 = forms.CharField(max_length=20, label='수납은행[1]')
    bank_number1 = forms.CharField(max_length=20, label='계좌번호[1]')
    bank_host1 = forms.CharField(max_length=15, label='예금주[1]')
    bank_account2 = forms.CharField(max_length=20, label='수납은행[2]', required=False)
    bank_number2 = forms.CharField(max_length=20, label='계좌번호[2]', required=False)
    bank_host2 = forms.CharField(max_length=15, label='예금주[2]', required=False)
    zipcode = forms.CharField(max_length=5, label='우편번호')
    address1 = forms.CharField(max_length=50, label='주소')
    address2 = forms.CharField(max_length=30, label='상세주소', required=False)
    address3 = forms.CharField(max_length=30, label='참고항목', required=False)
    title = forms.CharField(max_length=255, label='고지서 제목')
    content = forms.CharField(widget=forms.Textarea, label='고지서 내용')

    def __init__(self, project, *args, **kwargs):
        super(SalesBillIssueForm, self).__init__(*args, **kwargs)
        self.fields['now_payment_order'].queryset = InstallmentPaymentOrder.objects.filter(project=project)

app/django/apiV1/views/notice.py
from rest_framework import viewsets

from ..permission import *
from ..serializers.notice import *

from notice.models import SalesBillIssue


class BillIssueViewSet(viewsets.ModelViewSet):
    queryset = SalesBillIssue.objects.all()
    serializer_class = SallesBillIssueSerializer
    filterset_fields = ('project',)
    permission_classes = (permissions.IsAuthenticated, IsStaffOrReadOnly)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

app/django/notice/templates/notice/contractor_bill_publish.html
{% extends 'rebs/layouts/base.html' %}

{% load static widget_tweaks humanize %}

{% block title %}Rebs - 고객 고지 관리{% endblock %}

{% block content %}

    <!-- Start Content-->
    <div class="container-fluid">

        <!-- start page title -->
        {% include 'rebs/partials/content_title.html' with  second_bs="고객 고지 관리" title="수납 고지서 발행" %}
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">

                        {% with menu_order='1' %}
                            {% include 'notice/partials/head_menu.html' %}
                        {% endwith %}

                        <form class="form-horizontal p-0 col-12" name="form1" method="get">
                            <div class="row">
                                {% include 'rebs/partials/project_select.html' %}
                                <div class="col-sm-12 col-md-6"></div>
                            </div>
                        </form>

                        {% include 'notice/partials/bill_issue_form.html' %}
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body pb-1">

                        <div class="row mb-3 bg-light">
                            {% include 'notice/partials/contractor_search_form.html' %}
                        </div>
                        <div class="row">
                            {% include 'notice/partials/contractor_payment_list.html' %}
                        </div>

                        {% if is_paginated %}

                            {# to_first_last :: 맨처음 / 맨끝으로 버튼 사용 여부 #}
                            {# page_class ex:: pagination-rounded pagination-sm pagination-lg justify-content-center justify-content-end #}
                            {% include 'partials/pagination.html' with to_first_last="ok" page_class="pagination-rounded justify-content-end" %}

                        {% endif %}

                        <div class="row mt-2 mb-3 bg-dragula border-top border-bottom">
                            <div class="col-12 pt-2 pb-2 text-right">
                                {% if request.user.is_superuser or request.user.staffauth.notice > '1' %}
                                    <button type="button" class="btn btn-primary" onclick="print_bill()">선택 건별 고지서 다운로드하기</button>
                                {% else %}
                                    <button type="button" class="btn btn-outline-secondary"
                                            onclick="alert('수납 고지서 발행 권한이 없습니다. 관리자에게 문의하여 주십시요.')">조회권한 사용자</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- container -->

{% endblock %}

{% block third_party_js %}
    <script>
      const q = document.getElementById('id_q')

      window.onload = function () {
        document.getElementById('id_published_date').value = '{{ today }}'
        document.getElementById('id_project_sel').setAttribute('onchange', 'submit()')
        q.value = '{{ request.GET.q }}'
        q.setAttribute('onclick', 'this.value=\'\'')
      }

      function checkAll(handle, obj) { // 계약 항목 전체 선택
        var i;
        var chk = document.getElementsByName(obj);
        var tot = chk.length;
        if (handle.checked === true) {
          for (i = 0; i < tot; i++) {
            if (chk[i].disabled == false) chk[i].checked = true;
          }
        } else {
          for (i = 0; i < tot; i++) {
            chk[i].checked = false;
          }
        }
      }

      function print_bill() { // 필요한 데이터 가공 후 고지서 출력 파일로 이동
        var i;
        var chk = document.getElementsByName('chk[]');
        var seq = '';
        var j = 0;
        for (i = 0; i < chk.length; i++) { // get에 전달할 변수세트(계약자아이디+분양가아이디)를 "-"로 연결하기
          if (chk[i].checked == true) {
            sepwd = j == 0 ? "" : "-";
            seq += sepwd + chk[i].value;
            j++;
          }
        }
        var bill_issue = ('{{ bill_issue }}' == 'None') ? false : true;
        if (!bill_issue) {
          alert('고지서 관련 기본 설정 데이터를 입력하여 주십시요.');
          document.bill_set.host_name.focus()
          return;
        } else if (seq === '') {
          alert('다운로드(출력)할 계약 건을 선택하여 주십시요.');
          return;
        } else /* if (confirm('선택하신 건별 고지서를 다운로드하시겠습니까?')) */ {
          var pDate = document.bill_set.published_date.value;
          var uri = "{% url 'pdf:bill' %}" + "?project=" + {{ this_project.id }} +"&date=" + pDate + "&seq=" + seq;
          location.href = uri;
        }
      }
    </script>

    <!-- iOS에서는 position:fixed 버그가 있음, 적용하는 사이트에 맞게 position:absolute 등을 이용하여 top,left값 조정 필요 -->
    <div id="layer" style="display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;">
        <img src="//t1.daumcdn.net/postcode/resource/images/close.png" id="btnCloseLayer"
             style="cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1" onclick="closeDaumPostcode()"
             alt="닫기 버튼">
    </div>

    <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
    <script src="{% static 'common/js/daum_post_api.js' %}"></script>
{% endblock %}