app/django/_excel/urls.py
from django.urls import path
from .views import *

app_name = 'excel'

urlpatterns = [
    path('contracts/', ExportContracts.as_view(), name='contracts'),
    path('reservations/', ExportApplicants.as_view(), name='reservations'),
    path('releases/', ExportReleases.as_view(), name='releases'),
    path('status/', ExportUnitStatus.as_view(), name='unit-status'),
    # path('payments/', export_payments_xls, name='payments'),
    path('payments/', ExportPayments.as_view(), name='payments'),
    path('paid-by-cont/', ExportPaymentsByCont.as_view(), name='paid-by-cont'),
    path('paid-status/', ExportPaymentStatus.as_view(), name='paid-status'),
    path('p-balance/', ExportProjectBalance.as_view(), name='project-balance'),
    path('p-daily-cash/', ExportProjectDateCashbook.as_view(), name='project-daily-cash'),
    path('p-budget/', ExportBudgetExecutionStatus.as_view(), name='budget'),
    path('p-cashbook/', export_project_cash_xls, name='project-cash'),
    path('sites/', ExportSites.as_view(), name='sites'),
    path('sites-by-owner/', ExportSitesByOwner.as_view(), name='sites-by-owner'),
    path('sites-contracts/', ExportSitesContracts.as_view(), name='sites-contracts'),
    path('balance/', ExportBalanceByAcc.as_view(), name='balance'),
    path('daily-cash/', ExportDateCashbook.as_view(), name='daily-cash'),
    path('cashbook/', export_cashbook_xls, name='cashbook'),
]

app/django/api/urls.py
from django.urls import path

from rest_framework.response import Response
from rest_framework.reverse import reverse

from .views.accounts import *
from .views.company import *
from .views.rebs import *
from .views.project import *
from .views.cash import *
from .views.contract import *
from .views.notice import *
from .views.document import *


class ApiIndex(generics.GenericAPIView):
    name = 'api-index'
    permission_classes = (permissions.AllowAny,)

    def get(self, request, *args, **kwargs):
        api = 'api:'
        return Response({
            # accounts
            'user': reverse(api + 'user-list', request=request),
            'profile': reverse(api + 'profile-list', request=request),
            'todo': reverse(api + 'todo-list', request=request),
            # company
            'company': reverse(api + 'company-list', request=request),
            'logo': reverse(api + 'logo-list', request=request),
            'department': reverse(api + 'depart-list', request=request),
            'position': reverse(api + 'position-list', request=request),
            'staff': reverse(api + 'staff-list', request=request),
            # rebs
            'schedule': reverse(api + 'schedule-list', request=request),
            'account-sort': reverse(api + AccountSortList.name, request=request),
            'account-depth1': reverse(api + AccountSubD1List.name, request=request),
            'account-depth2': reverse(api + AccountSubD2List.name, request=request),
            'account-depth3': reverse(api + AccountSubD3List.name, request=request),
            'project-acc-sort': reverse(api + ProjectAccountSortList.name, request=request),
            'project-acc-d1': reverse(api + ProjectAccountD1List.name, request=request),
            'project-acc-d2': reverse(api + ProjectAccountD2List.name, request=request),
            'wise-say': reverse(api + WiseSayList.name, request=request),
            # project
            'project': reverse(api + 'project-list', request=request),
            'type': reverse(api + 'unittype-list', request=request),
            'floor': reverse(api + 'floortype-list', request=request),
            'key-unit': reverse(api + 'key_unit-list', request=request),
            'bldg-unit': reverse(api + 'bldg-list', request=request),
            'house-unit': reverse(api + HouseUnitList.name, request=request),
            'available-house-unit': reverse(api + AvailableHouseUnitList.name, request=request),
            'all-house-unit': reverse(api + AllHouseUnitList.name, request=request),
            'budget': reverse(api + ProjectBudgetList.name, request=request),
            'exec-amount-budget': reverse(api + ExecAmountToBudgetList.name, request=request),
            'all-site': reverse(api + AllSiteList.name, request=request),
            'sites-total': reverse(api + TotalSiteArea.name, request=request),
            'site': reverse(api + 'site-list', request=request),
            'all-owner': reverse(api + AllOwnerList.name, request=request),
            'owners-total': reverse(api + TotalOwnerArea.name, request=request),
            'site-owner': reverse(api + 'siteowner-list', request=request),
            'site-relation': reverse(api + 'relation-list', request=request),
            'conts-total': reverse(api + TotalContractedArea.name, request=request),
            'site-contract': reverse(api + 'sitecontract-list', request=request),
            # cash
            'bank-code': reverse(api + BankCodeList.name, request=request),
            'com-bank': reverse(api + 'com_bank-list', request=request),
            'balance-by-acc': reverse(api + BalanceByAccountList.name, request=request),
            'cashbook': reverse(api + CashBookList.name, request=request),
            'date-cashbook': reverse(api + DateCashBookList.name, request=request),
            'project-bank': reverse(api + ProjectBankAccountList.name, request=request),
            'pr-balance-by-acc': reverse(api + PrBalanceByAccountList.name, request=request),
            'pr-date-cashbook': reverse(api + ProjectDateCashBookList.name, request=request),
            'project-cashbook': reverse(api + ProjectCashBookList.name, request=request),
            'project-imprest': reverse(api + ProjectImprestList.name, request=request),
            'payment-list': reverse(api + PaymentList.name, request=request),
            'all-payment-list': reverse(api + AllPaymentList.name, request=request),
            'payment-sum': reverse(api + PaymentSummary.name, request=request),
            'cont-count': reverse(api + NumContractByType.name, request=request),
            'price': reverse(api + SalesPriceList.name, request=request),
            'pay-order': reverse(api + InstallmentOrderList.name, request=request),
            'down-payment': reverse(api + DownPaymentList.name, request=request),
            # 'over-due-rule': reverse(api + OverDueRuleList.name, request=request),
            # contract
            'order-group': reverse(api + 'order_group-list', request=request),
            'contract': reverse(api + 'contract-list', request=request),
            'contract-custom-list': reverse(api + 'contract-cumstom-list', request=request),
            'subs-sum': reverse(api + SubsSummaryList.name, request=request),
            'cont-sum': reverse(api + ContSummaryList.name, request=request),
            'contractor': reverse(api + 'contractor-list', request=request),
            'contractor-address': reverse(api + 'cont_address-list', request=request),
            'contractor-contact': reverse(api + 'contact-list', request=request),
            'contractor-release': reverse(api + 'release-list', request=request),
            # notice
            'sales-bill-issue': reverse(api + BillIssueList.name, request=request),
            # document
            'group': reverse(api + GroupList.name, request=request),
            'board': reverse(api + BoardList.name, request=request),
            'category': reverse(api + CategoryList.name, request=request),
            'suitcase': reverse(api + LawSuitCaseList.name, request=request),
            'post': reverse(api + PostList.name, request=request),
            'image': reverse(api + ImageList.name, request=request),
            'link': reverse(api + LinkList.name, request=request),
            'file': reverse(api + FileList.name, request=request),
            'comment': reverse(api + CommentList.name, request=request),
            'tag': reverse(api + TagList.name, request=request),
        })


app_name = 'api'

list_view = {'get': 'list', 'post': 'create'}
detail_view = {
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
}

urlpatterns = [
    # accounts
    path('', ApiIndex.as_view(), name=ApiIndex.name),
    path('user/', UserViewSets.as_view(list_view), name='user-list'),
    path('user/<int:pk>/', UserViewSets.as_view(detail_view), name='user-detail'),
    path('profile/', ProfileViewSets.as_view(list_view), name='profile-list'),
    path('profile/<int:pk>/', ProfileViewSets.as_view(detail_view), name='profile-detail'),
    path('todo/', TodoViewSets.as_view(list_view), name='todo-list'),
    path('todo/<int:pk>/', TodoViewSets.as_view(detail_view), name='todo-detail'),
    # company
    path('company/', CompanyViewSets.as_view(list_view), name='company-list'),
    path('company/<int:pk>/', CompanyViewSets.as_view(detail_view), name='company-detail'),
    path('logo/', LogoViewSets.as_view(list_view), name='logo-list'),
    path('logo/<int:pk>/', LogoViewSets.as_view(detail_view), name='logo-detail'),
    path('department/', DepartmentViewSets.as_view(list_view), name='depart-list'),
    path('department/<int:pk>/', DepartmentViewSets.as_view(detail_view), name='depart-detail'),
    path('position/', PositionViewSets.as_view(list_view), name='position-list'),
    path('position/<int:pk>/', PositionViewSets.as_view(detail_view), name='position-detail'),
    path('staff/', StaffViewSets.as_view(list_view), name='staff-list'),
    path('staff/<int:pk>/', StaffViewSets.as_view(detail_view), name='staff-detail'),
    # rebs
    path('schedule/', CalendarScheduleViewSet.as_view(list_view), name='schedule-list'),
    path('schedule/<int:pk>/', CalendarScheduleViewSet.as_view(detail_view), name='schedule-detail'),
    path('account-sort/', AccountSortList.as_view(), name=AccountSortList.name),
    path('account-depth1/', AccountSubD1List.as_view(), name=AccountSubD1List.name),
    path('account-depth2/', AccountSubD2List.as_view(), name=AccountSubD2List.name),
    path('account-depth3/', AccountSubD3List.as_view(), name=AccountSubD3List.name),
    path('project-acc-sort/', ProjectAccountSortList.as_view(), name=ProjectAccountSortList.name),
    path('project-account-depth1/', ProjectAccountD1List.as_view(), name=ProjectAccountD1List.name),
    path('project-account-depth2/', ProjectAccountD2List.as_view(), name=ProjectAccountD2List.name),
    path('wise-say/', WiseSayList.as_view(), name=WiseSayList.name),
    path('wise-say/<int:pk>/', WiseSayDetail.as_view(), name=WiseSayDetail.name),
    # project
    path('project/', ProjectViewSets.as_view(list_view), name='project-list'),
    path('project/<int:pk>/', ProjectViewSets.as_view(detail_view), name='project-detail'),
    path('type/', UnitTypeViewSets.as_view(list_view), name='unittype-list'),
    path('type/<int:pk>/', UnitTypeViewSets.as_view(detail_view), name='unittype-detail'),
    path('floor/', UnitFloorTypeViewSets.as_view(list_view), name='floortype-list'),
    path('floor/<int:pk>/', UnitFloorTypeViewSets.as_view(detail_view), name='floortype-detail'),
    path('key-unit/', KeyUnitViewSets.as_view(list_view), name='key_unit-list'),

app/django/contract/urls.py
from django.urls import path
from .views import *

app_name = 'contract'

urlpatterns = [
    path('', ContractLV.as_view(), name='index'),
    path('register/', ContractRegisterView.as_view(), name='register'),
    path('contractor/<int:pk>/', ContractorUpdate.as_view(), name='contractor'),
    path('trans/<int:pk>/', ContractorTrans.as_view(), name='trans'),
    path('release/register/', ContractorReleaseRegister.as_view(), name='release'),
    path('dashboard/', BuildDashboard.as_view(), name='dashboard'),
]

app/django/contract/forms.py
from django import forms

from .models import ContractorRelease
from cash.models import ProjectBankAccount, ProjectCashBook
from payment.models import InstallmentPaymentOrder


class ContractRegisterForm(forms.Form):
    project = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'project'}))
    task = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'task'}))
    order_group = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'order_group'}))
    type = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'type'}))
    key_unit = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'key_unit'}))
    house_unit = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'house_unit'}), required=False)
    back_url = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'back_url'}), required=False)

    # Contractor Model
    name = forms.CharField(max_length=10, label='계약자명')
    birth_date = forms.DateField(label='생년월일', required=False)
    GENDER_CHOICES = (('M', '남자'), ('F', '여자'))
    gender = forms.ChoiceField(widget=forms.RadioSelect, choices=GENDER_CHOICES, required=False, label='성별')
    is_registed = forms.BooleanField(label='인가등록 여부', required=False)
    reservation_date = forms.DateField(label='청약일자', required=False)
    contract_date = forms.DateField(label='계약일자', required=False)
    note = forms.CharField(widget=forms.Textarea, required=False, label='비고')
    # ContractorAddress Model
    id_zipcode = forms.CharField(max_length=5, label='우편번호', required=False)
    id_address1 = forms.CharField(max_length=50, label='주민등록 주소', required=False)
    id_address2 = forms.CharField(max_length=30, label='상세주소', required=False)
    id_address3 = forms.CharField(max_length=30, label='참고항목', required=False)
    dm_zipcode = forms.CharField(max_length=5, label='우편번호', required=False)
    dm_address1 = forms.CharField(max_length=50, label='우편송부 주소', required=False)
    dm_address2 = forms.CharField(max_length=30, label='상세주소', required=False)
    dm_address3 = forms.CharField(max_length=30, label='참고항목', required=False)
    # ContractorContact Model
    cell_phone = forms.CharField(max_length=13, label='휴대전화')
    home_phone = forms.CharField(max_length=13, required=False, label='집 전화')
    other_phone = forms.CharField(max_length=13, required=False, label='기타 전화')
    email = forms.EmailField(required=False, label='이메일')


class ContractorReleaseForm(forms.ModelForm):
    class Meta:
        model = ContractorRelease
        fields = '__all__'
        widgets = {
            'project': forms.HiddenInput(), 'contractor': forms.HiddenInput(),
            'status': forms.HiddenInput(), 'user': forms.HiddenInput()
        }


class ContractPaymentForm(forms.ModelForm):
    class Meta:
        model = ProjectCashBook
        fields = ('deal_date', 'income', 'bank_account', 'trader', 'installment_order')

    def __init__(self, project, *args, **kwargs):
        super(ContractPaymentForm, self).__init__(*args, **kwargs)
        self.fields['bank_account'].queryset = ProjectBankAccount.objects.filter(project=project)
        self.fields['bank_account'].empty_label = '납부계좌선택'
        self.fields['installment_order'].queryset = InstallmentPaymentOrder.objects.filter(project=project,
                                                                                           pay_code__lte='4')
        self.fields['installment_order'].empty_label = '납부회차선택'

app/django/contract/templates/contract/partials/contract_table.html
{% load humanize %}

<div class="col-12 table-responsive">
    {# 계약자 리스트 #}
    <div class="row">
        <div class="col-sm"><h5><i class="dripicons-view-apps text-primary"></i> 계약현황</h5></div>
        <div class="col-sm text-right mr-2">
            <span class="text-black-50 mr-3">총 계약 건수 : {{ contract_count }} 건</span>
            <a href="javascript:" onclick="$('#output_option').toggle();">[엑셀 출력항목 선택]</a>
            <a href="javascript:"
               onclick="excel('{% url 'excel:contracts' %}?project={{ this_project.id }}&group={{ request.GET.group }}&type={{ request.GET.type }}&dong={{ request.GET.dong }}&status={{ request.GET.status }}&reg={{ request.GET.register }}&sdate={{ request.GET.sdate }}&edate={{ request.GET.edate }}&q={{ request.GET.q }}')"
               class="ml-3">
                <i class="mdi mdi-file-excel-box"></i> Excel Export
                <i class="mdi mdi-download ml-1"></i>
            </a>
        </div>
    </div>

    <div class="col-sm-12 form-inline p-1 bg-info-lighten" id="output_option" style="display:none;">
        <div class="checkbox p-1"><label><input type="checkbox" name="opt1" class="mr-1" checked disabled> 일련번호&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt2" class="mr-1" checked> 인가여부&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt3" class="mr-1" checked> 차수&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt4" class="mr-1" checked> 타입&nbsp;</label></div>
        {% if this_project.is_unit_set %}
            <div class="checkbox p-1"><label><input type="checkbox" name="opt5" class="mr-1" checked> 동호수&nbsp;</label></div>
        {% endif %}
        <div class="checkbox p-1"><label><input type="checkbox" name="opt6" class="mr-1" checked> 계약자&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt7" class="mr-1" checked> 생년월일&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt8" class="mr-1" checked> 계약일자&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt9" class="mr-1" checked> 연락처[1]&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt10" class="mr-1"> 연락처[2]&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt11" class="mr-1"> 연락처[3]&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt12" class="mr-1"> 이메일&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt13" class="mr-1"> 주소[등본]&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt14" class="mr-1" checked> 주소[우편]&nbsp;</label></div>
        <div class="checkbox p-1"><label><input type="checkbox" name="opt15" class="mr-1"> 비고</label></div>
    </div>


    <table id="scroll-horizontal-datatable"
           class="table table-hover table-centered table-condensed table-sm w-100 m-0 nowrap"
           style="word-break: keep-all;">
        <thead>
        <tr class="bg-nav-pills">
            <th scope="col"><input type="checkbox" disabled></th>
            <th class="text-center" scope="col">일련 번호</th>
            <th class="text-center" scope="col">차 수</th>
            <th class="text-center" scope="col">타 입</th>
            {% if this_project.is_unit_set %}
                <th class="text-center" scope="col">동호수</th>{% endif %}
            <th class="text-center" scope="col">계약자</th>
            <th class="text-center" scope="col">최근 납입회차</th>
            <th class="text-center" scope="col">최근 납입금액</th>
            <th class="text-center" scope="col">인가 등록여부</th>
            <th class="text-center" scope="col">연락처[1]</th>
            <th class="text-center" scope="col">계약자 거주지역</th>
            <th class="text-center" scope="col">계약일자</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr class="{% if object.contractor.contractorrelease.status == '3' %}bg-warning-lighten{% endif %}">
                <th scope="row"><input type="checkbox" disabled></th>
                <td class="text-center" {% if object.contractor.status == '3' %}data-toggle="popover"
                    data-trigger="hover" title="" data-content="해지신청 상태" data-original-title=""{% endif %}>
                    <a href="{% url 'rebs:contract:register' %}?project={{ object.project_id }}&task=2&order_group={{ object.order_group.id }}&type={{ object.unit_type.id }}&key_unit={{ object.keyunit.id }}&house_unit={{ object.keyunit.houseunit.id }}&cont_id={{ object.id }}&p={{ request.GET.page }}&l={{ request.GET.limit }}&g={{ request.GET.group }}&t={{ request.GET.type }}&d={{ request.GET.dong }}&s={{ request.GET.status }}&r={{ request.GET.register }}&o={{ request.GET.order }}&sd={{ request.GET.sdate }}&ed={{ request.GET.edate }}&q={{ request.GET.q }}">
                        {{ object.serial_number }}
                    </a>
                </td>
                <td class="text-center">{{ object.order_group }}</td>
                <td><i class="mdi mdi-square"
                       style="color: {{ object.unit_type.color }};"></i> {{ object.unit_type }}
                </td>
                {% if this_project.is_unit_set %}
                    <td class="text-center">{{ object.keyunit.houseunit }}</td>{% endif %}
                <td class="text-center"
                    {% if object.contractor.contractorrelease.status == '3' %}data-toggle="popover"
                    data-trigger="hover" title="" data-content="해지신청 상태" data-original-title=""{% endif %}>
                    <a href="{% url 'rebs:contract:register' %}?project={{ object.project_id }}&task=2&order_group={{ object.order_group.id }}&type={{ object.unit_type.id }}&key_unit={{ object.keyunit.id }}&house_unit={{ object.keyunit.houseunit.id }}&cont_id={{ object.id }}&p={{ request.GET.page }}&l={{ request.GET.limit }}&g={{ request.GET.group }}&t={{ request.GET.type }}&d={{ request.GET.dong }}&s={{ request.GET.status }}&r={{ request.GET.register }}&o={{ request.GET.order }}&sd={{ request.GET.sdate }}&ed={{ request.GET.edate }}&q={{ request.GET.q }}">
                        {{ object.contractor.name }}
                    </a>
                </td>
                <td class="text-center">{{ object.payments.first.installment_order }}</td>
                <td class="text-right">{{ object.payments.first.income|intcomma }}</td>
                <td class="pl-5">
                    <i class="mdi mdi-circle text-{% if object.contractor.is_registed %}success{% else %}danger{% endif %}"></i>
                    {% if object.contractor.is_registed %}인가{% else %}미인가{% endif %}
                </td>
                <td class="text-center">{{ object.contractor.contractorcontact.cell_phone }}</td>
                <td class="text-center">{{ object.contractor.contractoraddress.dm_address1|truncatewords:"2" }}</td>
                <td class="text-center">{{ object.contractor.contract_date|date:"Y-m-d" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% block third_party_js %}
    <script>

      function excel(url){
			var opt = "1";
			if(document.form1.opt2.checked===true) var opt = opt+"-2";
			if(document.form1.opt3.checked===true) var opt = opt+"-3";
			if(document.form1.opt4.checked===true) var opt = opt+"-4";
        {% if this_project.is_unit_set %}
			if(document.form1.opt5.checked===true) var opt = opt+"-5-6";
        {% endif %}
			if(document.form1.opt6.checked===true) var opt = opt+"-7";
			if(document.form1.opt7.checked===true) var opt = opt+"-8";
			if(document.form1.opt8.checked===true) var opt = opt+"-9";
			if(document.form1.opt9.checked===true) var opt = opt+"-10";
			if(document.form1.opt10.checked===true) var opt = opt+"-11";
			if(document.form1.opt11.checked===true) var opt = opt+"-12";
			if(document.form1.opt12.checked===true) var opt = opt+"-13";
			if(document.form1.opt13.checked===true) var opt = opt+"-14-15-16-17";
			if(document.form1.opt14.checked===true) var opt = opt+"-18-19-20-21";
			if(document.form1.opt15.checked===true) var opt = opt+"-22";

			location.href = url+"&col="+opt;
		}
    </script>
{% endblock %}

app/django/contract/templates/contract/partials/head_menu.html
<ul class="nav nav-tabs mb-5">
    <li class="nav-item">
        <a href="{% url 'rebs:contract:index' %}{% if request.GET.project %}?project={{ request.GET.project }}{% endif %}"
           aria-expanded="{% if menu_order == '1' %}true{% else %}false{% endif %}"
           class="nav-link  {% if menu_order == '1' %}active{% endif %}">
            <i class="mdi mdi-deskphone d-md-none d-block"></i>
            <span class="d-none d-md-block">계약 현황 조회</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'rebs:contract:register' %}{% if request.GET.project %}?project={{ request.GET.project }}{% endif %}"
           aria-expanded="{% if menu_order == '2' %}true{% else %}false{% endif %}"
           class="nav-link {% if menu_order == '2' %}active{% endif %}">
            <i class="mdi mdi-format-list-bulleted d-md-none d-block"></i>
            <span class="d-none d-md-block">계약 등록 관리</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'rebs:contract:release' %}{% if request.GET.project %}?project={{ request.GET.project }}{% endif %}"
           aria-expanded="{% if menu_order == '3' %}true{% else %}false{% endif %}"
           class="nav-link {% if menu_order == '3' %}active{% endif %}">
            <i class="mdi mdi-format-list-bulleted d-md-none d-block"></i>
            <span class="d-none d-md-block">계약 해지 관리</span>
        </a>
    </li>
    <li class="nav-item">
        <a href="{% url 'rebs:contract:dashboard' %}{% if request.GET.project %}?project={{ request.GET.project }}{% endif %}"
           aria-expanded="{% if menu_order == '4' %}true{% else %}false{% endif %}"
           class="nav-link {% if menu_order == '4' %}active{% endif %}">
            <i class="mdi mdi-pencil-box-multiple-outline d-md-none d-block"></i>
            <span class="d-none d-md-block">동호수 현황표</span>
        </a>
    </li>
</ul>

app/django/contract/templates/contract/partials/release_table.html
{% load humanize %}

<div class="col-12 table-responsive">
    {# 계약자 리스트 #}
    <div class="row">
        <div class="col-sm"><h5><i class="dripicons-view-apps text-primary"></i> 계약해지 현황
        </h5></div>
        <div class="col-sm text-right mr-2">
            <span class="text-black-50">총 계약해지 건수 : {{ total_release }} 건</span>
            <a href="{% url 'excel:releases' %}?project={{ this_project.id }}" class="ml-3">
                <i class="mdi mdi-file-excel-box"></i> Excel Export
                <i class="mdi mdi-download ml-1"></i>
            </a>
        </div>
    </div>
    <table id="scroll-horizontal-datatable"
           class="table table-hover table-centered table-condensed table-sm w-100 m-0 nowrap"
           style="word-break: keep-all;">
        <thead>
        <tr class="bg-nav-pills">
            <th scope="col" rowspan="2"><input type="checkbox" disabled></th>
            <th class="text-center" rowspan="2" scope="col">계약 해지자</th>
            <th class="text-center" rowspan="2" scope="col">현재상태</th>
            <th class="text-center" rowspan="2" scope="col">환불(예정)금액</th>
            <th class="text-center" colspan="3" scope="col">환불계좌</th>
            <th class="text-center" rowspan="2" scope="col">해지신청일</th>
            <th class="text-center" rowspan="2" scope="col">환불처리일</th>
        </tr>
        <tr class="bg-nav-pills">
            <th class="text-center">은행명</th>
            <th class="text-center">계좌번호</th>
            <th class="text-center">예금주</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row"><input type="checkbox" disabled></th>
                <td class="text-center text-dark"
                        {% if object.note %}
                    data-toggle="tooltip"
                    data-placement="right" title=""
                    data-original-title="{{ object.note }}"
                        {% endif %}>
                    <a href="{% url 'rebs:contract:release' %}?project={{ this_project.id }}&task={{ object.status }}&contractor={{ object.contractor.id }}&release_id={{ object.id }}">
                        {{ object.contractor|truncatechars:"26" }}
                    </a>
                </td>
                <td class="text-center {% if object.status == '3' %}text-success{% else %}text-dark{% endif %}">{{ object.get_status_display }}</td>
                <td class="text-right">{{ object.refund_amount|default:"-"|intcomma }}</td>
                <td class="text-center">{{ object.refund_account_bank|default:"-" }}</td>
                <td class="text-center">{{ object.refund_account_number|default:"-" }}</td>
                <td class="text-center">{{ object.refund_account_depositor|default:"-" }}</td>
                <td class="text-center">{{ object.request_date|date:"Y-m-d" }}</td>
                <td class="text-center">{{ object.completion_date|date:"Y-m-d"|default:"-" }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>