app/django/api/urls.py
            'site-contract': reverse(api + 'sitecontract-list', request=request),
            # cash
            'bank-code': reverse(api + BankCodeList.name, request=request),
            'com-bank': reverse(api + 'com_bank-list', request=request),
            'balance-by-acc': reverse(api + BalanceByAccountList.name, request=request),
            'cashbook': reverse(api + CashBookList.name, request=request),
            'date-cashbook': reverse(api + DateCashBookList.name, request=request),
            'project-bank': reverse(api + ProjectBankAccountList.name, request=request),
            'pr-balance-by-acc': reverse(api + PrBalanceByAccountList.name, request=request),
            'pr-date-cashbook': reverse(api + ProjectDateCashBookList.name, request=request),
            'project-cashbook': reverse(api + ProjectCashBookList.name, request=request),
            'project-imprest': reverse(api + ProjectImprestList.name, request=request),
            'payment-list': reverse(api + PaymentList.name, request=request),
            'all-payment-list': reverse(api + AllPaymentList.name, request=request),
            'payment-sum': reverse(api + PaymentSummary.name, request=request),
            'cont-count': reverse(api + NumContractByType.name, request=request),
            'price': reverse(api + SalesPriceList.name, request=request),
            'pay-order': reverse(api + InstallmentOrderList.name, request=request),
            'down-payment': reverse(api + DownPaymentList.name, request=request),
            # 'over-due-rule': reverse(api + OverDueRuleList.name, request=request),
            # contract
            'order-group': reverse(api + 'order_group-list', request=request),
            'contract': reverse(api + 'contract-list', request=request),
            'contract-custom-list': reverse(api + 'contract-cumstom-list', request=request),
            'subs-sum': reverse(api + SubsSummaryList.name, request=request),
            'cont-sum': reverse(api + ContSummaryList.name, request=request),
            'contractor': reverse(api + 'contractor-list', request=request),
            'contractor-address': reverse(api + 'cont_address-list', request=request),
            'contractor-contact': reverse(api + 'contact-list', request=request),
            'contractor-release': reverse(api + 'release-list', request=request),
            # notice
            'sales-bill-issue': reverse(api + BillIssueList.name, request=request),
            # document
            'group': reverse(api + GroupList.name, request=request),
            'board': reverse(api + BoardList.name, request=request),
            'category': reverse(api + CategoryList.name, request=request),
            'suitcase': reverse(api + LawSuitCaseList.name, request=request),
            'post': reverse(api + PostList.name, request=request),
            'image': reverse(api + ImageList.name, request=request),
            'link': reverse(api + LinkList.name, request=request),
            'file': reverse(api + FileList.name, request=request),
            'comment': reverse(api + CommentList.name, request=request),
            'tag': reverse(api + TagList.name, request=request),
        })


app_name = 'api'

list_view = {'get': 'list', 'post': 'create'}
detail_view = {
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
}

urlpatterns = [
    # accounts
    path('', ApiIndex.as_view(), name=ApiIndex.name),
    path('user/', UserViewSets.as_view(list_view), name='user-list'),
    path('user/<int:pk>/', UserViewSets.as_view(detail_view), name='user-detail'),
    path('profile/', ProfileViewSets.as_view(list_view), name='profile-list'),
    path('profile/<int:pk>/', ProfileViewSets.as_view(detail_view), name='profile-detail'),
    path('todo/', TodoViewSets.as_view(list_view), name='todo-list'),
    path('todo/<int:pk>/', TodoViewSets.as_view(detail_view), name='todo-detail'),
    # company
    path('company/', CompanyViewSets.as_view(list_view), name='company-list'),
    path('company/<int:pk>/', CompanyViewSets.as_view(detail_view), name='company-detail'),
    path('logo/', LogoViewSets.as_view(list_view), name='logo-list'),
    path('logo/<int:pk>/', LogoViewSets.as_view(detail_view), name='logo-detail'),
    path('department/', DepartmentViewSets.as_view(list_view), name='depart-list'),
    path('department/<int:pk>/', DepartmentViewSets.as_view(detail_view), name='depart-detail'),
    path('position/', PositionViewSets.as_view(list_view), name='position-list'),
    path('position/<int:pk>/', PositionViewSets.as_view(detail_view), name='position-detail'),
    path('staff/', StaffViewSets.as_view(list_view), name='staff-list'),
    path('staff/<int:pk>/', StaffViewSets.as_view(detail_view), name='staff-detail'),
    # rebs
    path('schedule/', CalendarScheduleViewSet.as_view(list_view), name='schedule-list'),
    path('schedule/<int:pk>/', CalendarScheduleViewSet.as_view(detail_view), name='schedule-detail'),
    path('account-sort/', AccountSortList.as_view(), name=AccountSortList.name),
    path('account-depth1/', AccountSubD1List.as_view(), name=AccountSubD1List.name),
    path('account-depth2/', AccountSubD2List.as_view(), name=AccountSubD2List.name),
    path('account-depth3/', AccountSubD3List.as_view(), name=AccountSubD3List.name),
    path('project-acc-sort/', ProjectAccountSortList.as_view(), name=ProjectAccountSortList.name),
    path('project-account-depth1/', ProjectAccountD1List.as_view(), name=ProjectAccountD1List.name),
    path('project-account-depth2/', ProjectAccountD2List.as_view(), name=ProjectAccountD2List.name),
    path('wise-say/', WiseSayList.as_view(), name=WiseSayList.name),
    path('wise-say/<int:pk>/', WiseSayDetail.as_view(), name=WiseSayDetail.name),
    # project
    path('project/', ProjectViewSets.as_view(list_view), name='project-list'),
    path('project/<int:pk>/', ProjectViewSets.as_view(detail_view), name='project-detail'),
    path('type/', UnitTypeViewSets.as_view(list_view), name='unittype-list'),
    path('type/<int:pk>/', UnitTypeViewSets.as_view(detail_view), name='unittype-detail'),
    path('floor/', UnitFloorTypeViewSets.as_view(list_view), name='floortype-list'),
    path('floor/<int:pk>/', UnitFloorTypeViewSets.as_view(detail_view), name='floortype-detail'),
    path('key-unit/', KeyUnitViewSets.as_view(list_view), name='key_unit-list'),
    path('key-unit/<int:pk>/', KeyUnitViewSets.as_view(detail_view), name='key_unit-detail'),
    path('bldg/', BuildingUnitViewSets.as_view(list_view), name='bldg-list'),
    path('bldg/<int:pk>/', BuildingUnitViewSets.as_view(detail_view), name='bldg-detail'),
    path('house-unit/', HouseUnitList.as_view(), name=HouseUnitList.name),
    path('house-unit/<int:pk>/', HouseUnitDetail.as_view(), name=HouseUnitDetail.name),
    path('available-house-unit/', AvailableHouseUnitList.as_view(), name=AvailableHouseUnitList.name),
    path('all-house-unit/', AllHouseUnitList.as_view(), name=AllHouseUnitList.name),
    path('budget/', ProjectBudgetList.as_view(), name=ProjectBudgetList.name),
    # path('budget/<int:pk>/', ProjectBudgetDetail.as_view(), name=ProjectBudgetDetail.name),
    path('exec-amount/', ExecAmountToBudgetList.as_view(), name=ExecAmountToBudgetList.name),
    path('site/', SiteViewSets.as_view(list_view), name='site-list'),
    path('all-site/', AllSiteList.as_view(), name=AllSiteList.name),
    path('sites-total/', TotalSiteArea.as_view(), name=TotalSiteArea.name),
    path('site/<int:pk>/', SiteViewSets.as_view(detail_view), name='site-detail'),
    path('all-owner/', AllOwnerList.as_view(), name=AllOwnerList.name),
    path('owners-total/', TotalOwnerArea.as_view(), name=TotalOwnerArea.name),
    path('site-owner/', SiteOwnerViewSets.as_view(list_view), name='siteowner-list'),
    path('site-owner/<int:pk>/', SiteOwnerViewSets.as_view(detail_view), name='siteowner-detail'),
    path('site-relation/', SiteRelationViewSets.as_view(list_view), name='relation-list'),
    path('site-relation/<int:pk>/', SiteRelationViewSets.as_view(detail_view), name='relation-detail'),
    path('conts-total/', TotalContractedArea.as_view(), name=TotalContractedArea.name),
    path('site-contract/', SiteContractViewSets.as_view(list_view), name='sitecontract-list'),
    path('site-contract/<int:pk>/', SiteContractViewSets.as_view(detail_view), name='sitecontract-detail'),
    # cash
    path('bank-code/', BankCodeList.as_view(), name=BankCodeList.name),
    path('bank-code/<int:pk>/', BankCodeDetail.as_view(), name=BankCodeDetail.name),
    path('company-bank-account/', ComBankAccountViewSets.as_view(list_view), name='com_bank-list'),
    path('company-bank-account/<int:pk>/', ComBankAccountViewSets.as_view(detail_view), name='com_bank-detail'),
    path('balance-by-acc/', BalanceByAccountList.as_view(), name=BalanceByAccountList.name),
    path('cashbook/', CashBookList.as_view(), name=CashBookList.name),
    path('cashbook/<int:pk>/', CashBookDetail.as_view(), name=CashBookDetail.name),
    path('date-cashbook/', DateCashBookList.as_view(), name=DateCashBookList.name),
    path('project-bank-account/', ProjectBankAccountList.as_view(), name=ProjectBankAccountList.name),
    path('project-bank-account/<int:pk>/', ProjectBankAccountDetail.as_view(), name=ProjectBankAccountDetail.name),
    path('pr-balance-by-acc/', PrBalanceByAccountList.as_view(), name=PrBalanceByAccountList.name),
    path('pr-date-cashbook/', ProjectDateCashBookList.as_view(), name=ProjectDateCashBookList.name),
    path('project-cashbook/', ProjectCashBookList.as_view(), name=ProjectCashBookList.name),
    path('project-cashbook/<int:pk>/', ProjectCashBookDetail.as_view(), name=ProjectCashBookDetail.name),
    path('project-imprest/', ProjectImprestList.as_view(), name=ProjectImprestList.name),

app/django/rebs/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from .views import *

app_name = 'rebs'

urlpatterns = [
    path('', RedirectView.as_view(url='/rebs/dashboard/'), name='home'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('schedule/', menu2_1, name='menu2_1'),
    path('cash/', include('cash.urls')),
    path('company/', include('company.urls')),
    path('project/', include('project.urls')),
    path('contract/', include('contract.urls')),
    path('notice/', include('notice.urls')),
    path('docs/', include('document.urls')),
]

app/django/templates/rebs/layouts/partials/menu_company_cash.html
{% if request.user.is_superuser or request.user.staffauth.company_cash > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-money-stack"></i>
            <span> 본사 자금 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:cash-inout:report' %}">일별 자금 현황
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li>
                <a href="{% url 'rebs:cash-inout:index' %}">입출금 내역 조회
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li>
                <a href="{% url 'rebs:cash-inout:create' %}">입출금 내역 등록
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="javascript: void(0);" aria-expanded="false">관련 정보 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="#">은행 계좌 등록
                            <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">거래처 등록 관리
                            <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_company_docs.html
{% if request.user.is_superuser or request.user.staffauth.company_docs > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-file-plus-alt"></i>
            <span> 본사 문서 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:docs:co.general_list' %}">일반 문서 관리
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                </a>
            </li>
            {% if 'docs/general/add' in request.path %}
                <li>
                    <a href="{{ request.get_full_path }}">일반 문서 등록
                        <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                    </a>
                </li>
            {% endif %}
            {% if '1' in request.path or '2' in request.path or '3' in request.path or '4' in request.path or '5' in request.path or '6' in request.path or '7' in request.path or '8' in request.path or '9' in request.path %}
                {% if 'docs/general/' in request.path and 'update' not in request.path and 'delete' not in request.path %}
                    <li>
                        <a href="{{ request.get_full_path }}">일반 문서 열람
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                        </a>
                    </li>
                {% endif %}
                {% if 'docs/general/update' in request.path %}
                    <li>
                        <a href="{{ request.get_full_path }}">일반 문서 수정
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                        </a>
                    </li>
                {% endif %}
                {% if 'docs/general/delete' in request.path %}
                    <li>
                        <a href="{{ request.get_full_path }}">일반 문서 삭제
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                        </a>
                    </li>
                {% endif %}
            {% endif %}
            <li>
                <a href="javascript: void(0);" aria-expanded="false">법률 소송 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="{% url 'rebs:docs:co.lawsuit_list' %}">소송 문서 관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                        </a>
                    </li>
                    {% if 'docs/lawsuit/add' in request.path %}
                        <li>
                            <a href="{{ request.get_full_path }}">소송 문서 등록
                                <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                            </a>
                        </li>
                    {% endif %}
                    {% if '1' in request.path or '2' in request.path or '3' in request.path or '4' in request.path or '5' in request.path or '6' in request.path or '7' in request.path or '8' in request.path or '9' in request.path %}
                        {% if 'docs/lawsuit/' in request.path and 'update' not in request.path and 'delete' not in request.path %}
                            <li>
                                <a href="{{ request.get_full_path }}">소송 문서 열람
                                    <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if 'docs/lawsuit/update/' in request.path %}
                            <li>
                                <a href="{{ request.get_full_path }}">소송 문서 변경
                                    <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                                </a>
                            </li>
                        {% endif %}
                        {% if 'docs/lawsuit/delete' in request.path %}
                            <li>
                                <a href="{{ request.get_full_path }}">소송 문서 삭제
                                    <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li>
                        <a href="{% url 'rebs:docs:co.case_list' %}">소송 사건 관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                        </a>
                    </li>

                    {% if 'docs/lawsuit/case/add' in request.path and 'update' not in request.path %}
                        <li>
                            <a href="{{ request.get_full_path }}">소송 사건 등록
                                <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                            </a>
                        </li>
                    {% endif %}
                    {% if 'docs/lawsuit/case/update' in request.path %}
                        <li>
                            <a href="{{ request.get_full_path }}">소송 사건 변경
                                <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                            </a>
                        </li>
                    {% endif %}
                    {% if 'docs/lawsuit/case/delete' in request.path %}
                        <li>
                            <a href="{{ request.get_full_path }}">소송 사건 삭제
                                <span class="badge badge-pill badge-success-lighten font-10 float-right">ok</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_company_settings.html
{% if request.user.is_superuser or request.user.staffauth.company_settings > '0' or request.user.staffauth.auth_manage > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-cog"></i>
            <span> 환경 설정 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            {% if request.user.is_superuser or request.user.staffauth.company_settings > '0' %}
                <li>
                    <a href="{% url 'rebs:company:index' %}">회사 정보 관리
                        <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                    </a>
                </li>
            {% endif %}

            {% if request.user.is_superuser or request.user.staffauth.auth_manage > '0' %}
                <li>
                    <a href="#">권한 설정 관리
                        <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_contract.html
{% if request.user.is_superuser or request.user.staffauth.contract > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-file-contract-dollar"></i>
            <span> 분양 계약 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:contract:index' %}">계약 현황 조회
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="javascript: void(0);" aria-expanded="false">
                    계약 정보 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="{% url 'rebs:contract:register' %}">계약 등록 관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:contract:release' %}">계약 해지 관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{% url 'rebs:contract:dashboard' %}">동호수 현황표
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_dashboard.html
<li class="side-nav-item">
    <a href="{% url 'rebs:dashboard' %}" class="side-nav-link">
        <i class="uil-tachometer-fast"></i>
        {#                    <span class="badge badge-success float-right">4</span>#}
        <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
        <span> 대시보드 </span>
    </a>
</li>

app/django/templates/rebs/layouts/partials/menu_humanresource.html
{% if request.user.is_superuser or request.user.staffauth.human_resource > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-users-alt"></i>
            <span> 본사 인사 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="#">직원 정보 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>
            <li>
                <a href="#">성과 정보 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>
            <li class="side-nav-item">
                <a href="javascript: void(0);" aria-expanded="false">
                    관련 정보 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="#">부서 정보 관리
                            <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">직급 정보 관리
                            <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_new_project.html
{% if request.user.is_superuser or request.user.staffauth.project > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-map-marker-plus"></i>
            <span> 신규 프로젝트 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:project:index' %}">프로젝트 관리
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            {% if 'project/create' in request.path %}
                <li>
                    <a href="{{ request.path }}">프로젝트 등록
                        <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                    </a>
                </li>
            {% endif %}
            {% if 'project/update' in request.path %}
                <li>
                    <a href="{{ request.path }}">프로젝트 수정
                        <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                    </a>
                </li>
            {% endif %}
            {% if 'project/delete' in request.path %}
                <li>
                    <a href="{{ request.path }}">프로젝트 삭제
                        <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                    </a>
                </li>
            {% endif %}
            <li class="side-nav-item">
                <a href="javascript: void(0);" aria-expanded="false">
                    세부 정보 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="{% url 'rebs:project:set-ordergroup' %}">차수 분류 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:set-unit-type' %}">타입 정보 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:set-floor-type' %}">층별 조건 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:set-sales-price' %}">분양 가격 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:set-payment-order' %}">납부 회차 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:set-down-payment' %}">계약 금액 등록
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="side-nav-item">
                <a href="javascript: void(0);" aria-expanded="false">
                    사업 부지 관리
                    <span class="menu-arrow"></span>
                </a>
                <ul class="side-nav-third-level" aria-expanded="false">
                    <li>
                        <a href="{% url 'rebs:project:site' %}">지번 별 토지관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:site-owner' %}">소유자별 토지관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'rebs:project:site-contract' %}">사업부지 매입관리
                            <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_notice.html
{% if request.user.is_superuser or request.user.staffauth.notice > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-envelope-add"></i>
            <span> 고객 고지 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:notice:bill' %}">
                    수납 고지서 발행
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li>
                <a href="#">
                    SMS 발송 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>
            <li>
                <a href="#">
                    MAIL 발송 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>
            <li>
                <a href="#">
                    우편 라벨 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>

            <li>
                <a href="#">발송 기록 관리
                    <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
                </a>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_payment.html
{% if request.user.is_superuser or request.user.staffauth.payment > '0' %}
    <li class="side-nav-item">
        <a href="javascript: void(0);" class="side-nav-link">
            <i class="uil-money-bill-stack"></i>
            <span> 분양 수납 관리 </span>
            <span class="menu-arrow"></span>
        </a>
        <ul class="side-nav-second-level" aria-expanded="false">
            <li>
                <a href="{% url 'rebs:cash-inout:payment-index' %}">분양 수납 내역
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
            <li>
                <a href="{% url 'rebs:cash-inout:payment-register' %}">건별 수납 관리
                    <span class="badge badge-pill badge-success-lighten font-10 float-right">Ok</span>
                </a>
            </li>
        </ul>
    </li>
{% endif %}

app/django/templates/rebs/layouts/partials/menu_schedule.html
<li class="side-nav-item">
    <a href="{% url 'rebs:menu2_1' %}" class="side-nav-link">
        <i class="uil-schedule"></i>
        <span> 일정 관리 </span>
        <span class="badge badge-pill badge-light-lighten font-10 float-right">준비중..</span>
    </a>
</li>